#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    S = input()
    N = len(S)
    ans = N * (N - 1)
    for i in range(1, N - 1):
        if S[i] == 'U':
            ans += i
        else:
            ans += N - i - 1

    print(ans)
    return

if __name__ == '__main__':
    main()
