#!/usr/bin/env python3
import sys


def solve(N: int, h: "List[int]"):
    ans = 0
    for i in range(max(h) + 1):
        if h[0] > i:
            ans += 1
        for j in range(1, N):
            if h[j-1] <= i and h[j] > i:
                ans += 1

    print(ans)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    h = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, h)

if __name__ == '__main__':
    main()
