#!/usr/bin/env python3
import sys

def solve(n: int, a: "List[int]"):
    ans = [None] * n
    left, right = 0, n - 1
    for i in range(n):
        if i % 2 == 0:
            ans[left] = a[-(i + 1)]
            left += 1
        else:
            ans[right] = a[-(i + 1)]
            right -= 1

    print(*ans)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    n = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(n)]  # type: "List[int]"
    solve(n, a)

if __name__ == '__main__':
    main()
