#!/usr/bin/env python3
from collections import Counter
import sys

def is_all(S, ch):
    judge = True
    for s in S:
        if s != ch:
            judge = False
            break

    return judge


def solve(s: str):
    ans = 0
    for c in set(s):
        N = len(s)
        T = s
        while True:
            if is_all(T, c):
                ans = max(ans, len(T))
                break
            else:
                temp = ''
                for i in range(len(T)-1):
                    if T[i] == c or T[i+1] == c:
                        temp += c
                    else:
                        temp += T[i]
                T = temp

    print(len(s) - ans)      
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    s = next(tokens)  # type: str
    solve(s)

if __name__ == '__main__':
    main()
